name: community-cloud-storage

services:
  ipfs:
    image: ipfs/kubo:v0.36.0
    network_mode: host
    environment:
    volumes:
      - ipfs:/data/ipfs
    restart: unless-stopped

  ipfs-cluster:
    image: ipfs/ipfs-cluster:latest
    network_mode: host
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: ${CLUSTER_PEERNAME}
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /ip4/127.0.0.1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s
      # Replication settings
      CLUSTER_REPLICATIONFACTORMIN: "2"
      CLUSTER_REPLICATIONFACTORMAX: "3"
      CLUSTER_DISABLEREPINNING: "false"
    volumes:
      - ipfs-cluster:/data/ipfs-cluster
    restart: unless-stopped

volumes:
  ipfs:
  ipfs-cluster:
